### ISSUE TITLE
Error jobs for Access on peviitor.ro site

### ISSUE THREAD

**Issue by GabyRP06** [peviitor-ro/issues#286]
ENVIRONMENT: PROD
url: https://peviitor.ro/
browser: Chrome

STEPS TO REPRODUCE:
1)open url in the browser
2)type Access in the search bar
3)check the number of jobs

EXPECTED RESULTS:
All jobs displayed should be for Access company.

ACTUAL RESULTS:
Are displayed 77 jobs, 52 jobs are for Access, 25 jobs are for another company's ( access is mentioned only in job title).
![error jobs  Access ](https://github.com/peviitor-ro/issues/assets/123496277/d5c1b4d0-8443-4060-a546-95fe63f2df3d)
![joburi access](https://github.com/peviitor-ro/issues/assets/123496277/bf0b8c8e-edce-4156-962b-0ab1f1ca9a46)

**Comment by melania23m** [comment]
![image](https://github.com/peviitor-ro/issues/assets/112417484/415c2e54-3132-4cb2-a055-b95ab7b9b249)
![image](https://github.com/peviitor-ro/issues/assets/112417484/0b6a417a-5bb3-4487-94f6-3d4d86d2aa8a)
because the company is named 'AccessGroup' I changed the name and now it should be ok, all jobs are for Accessgroup company.

**Comment by GabyRP06** [comment]
for this topic is ok. I will close this bug.
